#!/usr/bin/env python3
# Copyright 2026 Ego Hygiene
# SPDX-License-Identifier: MIT

"""Build a Beacon research-paper project into PDF, HTML, and arXiv source."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import html as html_module
import io
import json
import os
import re
import shutil
import subprocess
import tarfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "beacon-template.toml"
INPUT_PATTERN = re.compile(r"\\input\{([^}]+)\}")
FIGURE_PATTERN = re.compile(
    r"\\BeaconFigure\{([^{}]+)\}\{([^{}]+)\}\{([^{}]+)\}", re.DOTALL
)


def load_toml(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def resolve_from_cwd(value: str) -> Path:
    path = Path(value).expanduser()
    return path.resolve() if path.is_absolute() else (Path.cwd() / path).resolve()


def run(command: list[str], *, cwd: Path, env: dict[str, str] | None = None) -> None:
    print("+ " + " ".join(command))
    subprocess.run(command, cwd=cwd, env=env, check=True)


def tex_escape(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def git_revision(path: Path, fallback: str) -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(path), "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return fallback


def author_lines(authors: list[dict]) -> tuple[str, str, str]:
    rendered_authors: list[str] = []
    affiliations: list[str] = []
    credit_parts: list[str] = []
    for author in authors:
        name = tex_escape(author["name"])
        affiliation = tex_escape(author.get("affiliation", "Independent researcher"))
        details: list[str] = []
        if author.get("email"):
            email = tex_escape(author["email"])
            details.append(rf"\href{{mailto:{email}}}{{{email}}}")
        if author.get("orcid"):
            orcid = tex_escape(author["orcid"])
            details.append(rf"\href{{https://orcid.org/{orcid}}}{{ORCID {orcid}}}")
        rendered_authors.append(name + (rf" \textnormal{{\small ({'; '.join(details)})}}" if details else ""))
        if affiliation not in affiliations:
            affiliations.append(affiliation)
        roles = ", ".join(tex_escape(role) for role in author.get("credit_roles", []))
        credit_parts.append(f"{name}: {roles or 'contributor roles not yet assigned'}")
    return (
        r" \\[0.22em] ".join(rendered_authors),
        r" \\ ".join(affiliations),
        "; ".join(credit_parts) + ".",
    )


def write_generated_metadata(
    destination: Path, config: dict, revision: str, template_version: str
) -> None:
    paper = config["paper"]
    provenance = config["provenance"]
    authors, affiliations, credits = author_lines(paper["authors"])
    commands = {
        "BeaconPaperTitle": tex_escape(paper["title"]),
        "BeaconPaperSubtitle": tex_escape(paper.get("subtitle", "")),
        "BeaconPaperVersion": tex_escape(paper["version"]),
        "BeaconPaperDate": tex_escape(paper["date"]),
        "BeaconPaperAuthors": authors,
        "BeaconPaperAffiliations": affiliations,
        "BeaconPaperAbstract": tex_escape(paper["abstract"]),
        "BeaconPaperKeywords": tex_escape(", ".join(paper["keywords"])),
        "BeaconPaperRepository": tex_escape(provenance["source_repository"]),
        "BeaconPaperRevision": tex_escape(revision),
        "BeaconContributorStatement": credits,
    }
    lines = ["% Generated by Beacon. Edit beacon-project.toml, not this file."]
    lines.extend(rf"\renewcommand{{\{name}}}{{{value}}}" for name, value in commands.items())
    lines.append(rf"\newcommand{{\BeaconTemplateVersion}}{{{tex_escape(template_version)}}}")
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")

    provenance_lines = [
        "% Generated by Beacon. Included in the arXiv source bundle.",
        rf"\newcommand{{\BeaconSourceRepository}}{{{tex_escape(provenance['source_repository'])}}}",
        rf"\newcommand{{\BeaconSourceRevision}}{{{tex_escape(revision)}}}",
        rf"\newcommand{{\BeaconSourcePath}}{{{tex_escape(provenance.get('source_path', '.'))}}}",
        rf"\newcommand{{\BeaconSourceLicense}}{{{tex_escape(provenance.get('license', 'unspecified'))}}}",
    ]
    (destination.parent / "beacon-generated-provenance.tex").write_text(
        "\n".join(provenance_lines) + "\n", encoding="utf-8"
    )


def convert_figures(work: Path) -> None:
    figure_dir = work / "paper" / "figures"
    if not figure_dir.exists():
        return
    for source in sorted(figure_dir.glob("*.svg")):
        destination = source.with_suffix(".pdf")
        if shutil.which("rsvg-convert"):
            run(
                ["rsvg-convert", "--format", "pdf", "--output", str(destination), str(source)],
                cwd=work,
            )
        elif shutil.which("inkscape"):
            run(
                [
                    "inkscape",
                    str(source),
                    "--export-type=pdf",
                    f"--export-filename={destination}",
                ],
                cwd=work,
            )
        else:
            raise RuntimeError("SVG figures require rsvg-convert or inkscape")


def expand_inputs(path: Path, source_root: Path, seen: set[Path] | None = None) -> str:
    seen = set() if seen is None else seen
    resolved = path.resolve()
    if resolved in seen:
        raise RuntimeError(f"recursive LaTeX input: {resolved}")
    seen.add(resolved)
    text = resolved.read_text(encoding="utf-8")

    def replace(match: re.Match[str]) -> str:
        target = match.group(1)
        candidate = (source_root / target).with_suffix(".tex")
        if not candidate.exists():
            candidate = (resolved.parent / target).with_suffix(".tex")
        candidate = candidate.resolve()
        if source_root not in candidate.parents and candidate != source_root:
            raise RuntimeError(f"LaTeX input escapes project: {target}")
        return expand_inputs(candidate, source_root, seen.copy())

    return INPUT_PATTERN.sub(replace, text)


def web_source(work: Path, entrypoint: str) -> str:
    expanded = expand_inputs(work / entrypoint, work)
    body_match = re.search(r"\\begin\{document\}(.*)\\end\{document\}", expanded, re.DOTALL)
    if body_match is None:
        raise RuntimeError("paper entrypoint must contain a document environment")
    body = body_match.group(1)
    body = body.replace(r"\BeaconMakeTitle", "")
    body = re.sub(r"\\bibliographystyle\{[^}]+\}", "", body)
    body = re.sub(r"\\bibliography\{[^}]+\}", "", body)
    body = re.sub(r"\\appendix\s*", lambda _: r"\section*{Appendix}", body)

    def figure(match: re.Match[str]) -> str:
        slug, caption, description = (part.strip() for part in match.groups())
        return (
            "\n\\begin{figure}\n\\centering\n"
            f"\\includegraphics{{figures/{slug}.svg}}\n"
            f"\\caption{{{caption}}}\n\\end{{figure}}\n\n"
            f"\\textit{{Figure description:}} {description}\n"
        )

    return FIGURE_PATTERN.sub(figure, body)


def build_web(work: Path, output: Path, config: dict, theme: dict) -> None:
    paper = config["paper"]
    web_dir = output / "web"
    web_dir.mkdir(parents=True, exist_ok=True)
    figure_dir = work / "paper" / "figures"
    if figure_dir.exists():
        web_figures = web_dir / "figures"
        web_figures.mkdir(exist_ok=True)
        for source in sorted(figure_dir.glob("*.svg")):
            shutil.copy2(source, web_figures / source.name)

    source = work / "paper-for-web.tex"
    figure_records = FIGURE_PATTERN.findall(
        expand_inputs(work / config["paper"]["entrypoint"], work)
    )
    source_text = web_source(work, config["paper"]["entrypoint"])
    source.write_text(source_text, encoding="utf-8")
    metadata = {
        "title": paper["title"],
        "subtitle": paper.get("subtitle", ""),
        "author": [author["name"] for author in paper["authors"]],
        "abstract": paper["abstract"],
        "keywords": paper["keywords"],
        "date": paper["date"],
        "version": paper["version"],
        "lang": paper["language"],
        "project_id": paper["id"],
        "theme_label": theme["label"],
        **{f"theme_{key}": theme[key] for key in ("primary", "accent", "surface", "ink", "muted")},
    }
    metadata_path = work / "web-metadata.json"
    metadata_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    html_path = web_dir / "index.html"
    run(
        [
            "pandoc",
            str(source),
            "--from=latex",
            "--to=html5",
            "--standalone",
            "--citeproc",
            f"--bibliography={work / paper['bibliography']}",
            f"--metadata-file={metadata_path}",
            f"--template={ROOT / 'web' / 'paper.html'}",
            "--mathml",
            "--section-divs",
            "--table-of-contents",
            f"--output={html_path}",
        ],
        cwd=web_dir,
    )
    rendered = html_path.read_text(encoding="utf-8")
    for slug, caption, _ in figure_records:
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", slug):
            raise RuntimeError(f"unsafe figure slug: {slug}")
        image_pattern = re.compile(
            rf'<img src="figures/{re.escape(slug)}\.svg"\s*/?>'
        )
        image = (
            f'<img src="figures/{slug}.svg" '
            f'alt="{html_module.escape(caption.strip(), quote=True)}">'
        )
        rendered, replacements = image_pattern.subn(image, rendered)
        if replacements != 1:
            raise RuntimeError(f"web projection did not emit figure image: {slug}")
    html_path.write_text(rendered, encoding="utf-8")


def archive_arxiv(
    work: Path, output: Path, config: dict, epoch: int, theme_id: str
) -> Path:
    paper = config["paper"]
    files: list[tuple[Path, str]] = []
    for name in (
        "main.tex",
        "main.bbl",
        "beacon-research-paper.sty",
        f"beacon-theme-{theme_id}.sty",
        "beacon-generated-metadata.tex",
        "beacon-generated-provenance.tex",
    ):
        source = work / name if name != "main.bbl" else work / "latex-out" / name
        if source.exists():
            files.append((source, name))
    for source in sorted((work / "paper").rglob("*")):
        if source.is_file() and source.suffix.lower() in {".tex", ".bib", ".pdf", ".png", ".jpg", ".jpeg"}:
            files.append((source, source.relative_to(work).as_posix()))

    memory = io.BytesIO()
    with tarfile.open(fileobj=memory, mode="w", format=tarfile.GNU_FORMAT) as archive:
        for source, archive_name in sorted(files, key=lambda pair: pair[1]):
            info = archive.gettarinfo(str(source), arcname=archive_name)
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            info.mtime = epoch
            info.mode = 0o644
            with source.open("rb") as stream:
                archive.addfile(info, stream)

    arxiv_dir = output / "arxiv"
    arxiv_dir.mkdir(parents=True, exist_ok=True)
    destination = arxiv_dir / f"{paper['id']}-{paper['version']}.tar.gz"
    with destination.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=epoch) as compressed:
            compressed.write(memory.getvalue())
    return destination


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--theme")
    arguments = parser.parse_args()

    project = resolve_from_cwd(arguments.project)
    output = resolve_from_cwd(arguments.output)
    if output in {project, ROOT, Path("/")} or output in project.parents:
        raise SystemExit("refusing unsafe output directory")
    config_path = project / "beacon-project.toml"
    config = load_toml(config_path)
    manifest = load_toml(MANIFEST)
    theme_id = arguments.theme or config["beacon"]["theme"]
    theme_path = ROOT / "themes" / f"{theme_id}.toml"
    if not theme_path.is_file():
        raise SystemExit(f"unknown theme: {theme_id}")
    theme = load_toml(theme_path)
    epoch = int(config["provenance"]["source_date_epoch"])
    revision = git_revision(project, config["provenance"].get("source_revision", "working-tree"))

    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    work = output / "source"
    shutil.copytree(project / "paper", work / "paper")
    for style in sorted((ROOT / "latex").glob("*.sty")):
        shutil.copy2(style, work / style.name)
    write_generated_metadata(work / "beacon-generated-metadata.tex", config, revision, manifest["version"])
    (work / "main.tex").write_text(
        f"\\PassOptionsToPackage{{{theme_id}}}{{beacon-research-paper}}\n"
        f"\\input{{{config['paper']['entrypoint']}}}\n",
        encoding="utf-8",
    )
    convert_figures(work)

    latex_output = work / "latex-out"
    latex_output.mkdir()
    environment = os.environ.copy()
    environment.update(
        {
            "SOURCE_DATE_EPOCH": str(epoch),
            "FORCE_SOURCE_DATE": "1",
            "TZ": "UTC",
            "TEXINPUTS": f"{work}{os.pathsep}" + environment.get("TEXINPUTS", ""),
        }
    )
    run(
        [
            "latexmk",
            "-pdf",
            "-interaction=nonstopmode",
            "-halt-on-error",
            "-file-line-error",
            f"-outdir={latex_output}",
            "main.tex",
        ],
        cwd=work,
        env=environment,
    )
    shutil.copy2(latex_output / "main.pdf", output / "paper.pdf")
    shutil.copy2(latex_output / "main.log", output / "paper.log")
    build_web(work, output, config, theme)
    archive = archive_arxiv(work, output, config, epoch, theme_id)

    provenance = {
        "schema_version": 1,
        "profile": manifest["id"],
        "template_version": manifest["version"],
        "theme": theme_id,
        "project_id": config["paper"]["id"],
        "project_version": config["paper"]["version"],
        "source_repository": config["provenance"]["source_repository"],
        "source_path": config["provenance"].get("source_path", "."),
        "source_revision": revision,
        "source_date_epoch": epoch,
        "artifacts": {
            "paper.pdf": sha256(output / "paper.pdf"),
            "web/index.html": sha256(output / "web" / "index.html"),
            f"arxiv/{archive.name}": sha256(archive),
        },
    }
    (output / "provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"Built {output / 'paper.pdf'}")
    print(f"Built {output / 'web' / 'index.html'}")
    print(f"Built {archive}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
