$pdf_mode = 1;
$out_dir = 'build';
$aux_dir = 'build';
$ENV{'TEXINPUTS'} = '.:styles//:' . ($ENV{'TEXINPUTS'} || '');
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex = 'bibtex %O %B';
$bibtex_use = 1;
$cleanup_includes_cusdep_generated = 1;
