$pdf_mode = 1;
$beacon_build_dir = $ENV{'BEACON_BUILD_DIR'} || 'build';
$out_dir = $beacon_build_dir;
$aux_dir = $beacon_build_dir;
$ENV{'TEXINPUTS'} = '.:styles//:' . ($ENV{'TEXINPUTS'} || '');
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex = 'bibtex %O %B';
$bibtex_use = 1;
$cleanup_includes_cusdep_generated = 1;
